server {
    listen 8080;
    server_name play.morm.one;
    client_max_body_size 512m;
    location / {
        proxy_pass http://127.0.0.1:8791;
        proxy_set_header Host $host;
        proxy_set_header Range $http_range;
        proxy_http_version 1.1;
        proxy_buffering off;
    }
}
